parameters:
#    poyecto_proyecto.example.class: Poyecto\ProyectoBundle\Example

services:
#    poyecto_proyecto.example:
#        class: %poyecto_proyecto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
