Poyecto\ProyectoBundle\Entity\DetalleProducto1:
    type: entity
    table: null
    repositoryClass: Poyecto\ProyectoBundle\Entity\DetalleProducto1Repository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        cantidad:
            type: string
            length: 255
        detalle:
            type: string
            length: 255
        valorunitario:
            type: string
            length: 255
        valortotal:
            type: string
            length: 255
        idnotaventa:
            type: string
            length: 255
    lifecycleCallbacks: {  }
