<?php

namespace Poyecto\ProyectoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleProducto1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProducto1Repository extends EntityRepository
{

	public function obtenerListaReporte()
	{
		$query = "SELECT
		nv.fecha as fecha,
		nv.vendedor AS vendedor, 
		dp.idnotaventa AS idnotaventa,
		dp.detalle AS nombreProducto,
		dp.cantidad AS cantidad,
		dp.valorunitario AS valorUnitario,
		dp.valortotal AS valorTotal

		FROM Poyecto\ProyectoBundle\Entity\DetalleProducto1 dp
		LEFT JOIN Poyecto\ProyectoBundle\Entity\NotaVenta1 nv WITH (nv.id = dp.idnotaventa)
		WHERE 1=1";

		$query = $this->_em->createQuery($query);
        //echo'<pre>';var_dump($query->getArrayResult());exit;      
        return $query->getArrayResult();
	}

public function obtenerDetallesProductos($parametros)
	{

		$query = "SELECT
		nv.fecha as fecha,
		nv.vendedor AS vendedor, 
		dp.detalle AS nombreProducto,
		dp.cantidad AS cantidad,
		dp.valorUnitario AS valorUnitario,
		dp.valorTotal AS valorTotal 
		
		FROM Rebsol\HermesBundle\Entity\AccionClinicaPaciente acp
		LEFT JOIN Rebsol\HermesBundle\Entity\Paciente pa WITH (pa.id       = acp.idPaciente)
		JOIN Rebsol\HermesBundle\Entity\Pnatural pnat WITH (pnat.id        = pa.idPnatural)
		JOIN Rebsol\HermesBundle\Entity\Persona per WITH (per.id           = pnat.idPersona)
		LEFT JOIN Rebsol\HermesBundle\Entity\Prevision prev WITH (prev.id  = pa.idConvenio)
		JOIN Rebsol\HermesBundle\Entity\Prevision prev2 with (prev2.id     = pa.idFinanciador)
		LEFT JOIN Rebsol\HermesBundle\Entity\AccionClinica ac WITH (ac.id  = acp.idAccionClinica)
		LEFT JOIN Rebsol\HermesBundle\Entity\TipoAtencionFc ta WITH (ta.id = pa.idTipoAtencionFc)
		JOIN Rebsol\HermesBundle\Entity\Bodega bod WITH (bod.id            = acp.idBodega)
		JOIN Rebsol\HermesBundle\Entity\Servicio ser WITH (ser.id          = bod.idServicio)
		JOIN Rebsol\HermesBundle\Entity\Unidad uni WITH (uni.id            = ser.idUnidad)
		JOIN Rebsol\HermesBundle\Entity\Sucursal suc WITH (suc.id          = uni.idSucursal)

		WHERE per.idEmpresa = :idEmpresa
		AND acp.idEstadoAccionClinica > 2  
        AND acp.fechaSolicitud BETWEEN :fechaMin AND :fechaMax
        AND suc.id = :idSucursal
        AND uni.id = :idUnidad
        AND ser.id = :idServicio
        AND bod.id = :idBodega";

		$query = $this->_em->createQuery($query);
        
         if($parametros['idSucursal'] != null){
   	 		$query->setParameter('idSucursal', $parametros['idSucursal']);
   	 	}

   	 	 if($parametros['idUnidad'] != null){
   	 		$query->setParameter('idUnidad', $parametros['idUnidad']);
   	 	}

   	 	 if($parametros['idServicio'] != null){
   	 		$query->setParameter('idServicio', $parametros['idServicio']);
   	 	}

   	 	 if($parametros['idBodega'] != null){
   	 		$query->setParameter('idBodega', $parametros['idBodega']);
   	 	}

        $query->setParameter('idEmpresa', $this->obtenerEmpresaLogin()); 	 	
        $query->setParameter('fechaMin', $parametros['fechaMin']." 00:00:00");
        $query->setParameter('fechaMax', $parametros['fechaMax']." 23:59:59");
        
        return $query->getArrayResult();
	}
}
