<?php

namespace Poyecto\ProyectoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProductoRepository extends EntityRepository
{
}
