<?php

namespace Poyecto\ProyectoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotaVenta1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaVenta1Repository extends EntityRepository
{
}
